global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  # Scrape TimescaleDB exporter
  - job_name: "timescaledb"
    static_configs:
      - targets: ["timescaledb:9187"]

  - job_name: promscale
    static_configs:
      - targets: ["promscale:9201"]

remote_write:
  - url: "http://timescaledb_prometheus_adapter:9201/write"
remote_read:
  - url: "http://timescaledb_prometheus_adapter:9201/read"
    read_recent: true
