global:
  scrape_interval: 15s # How often to scrape targets by default.

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Redis exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]

  # Scrape TimescaleDB exporter
  - job_name: "timescaledb"
    static_configs:
      - targets: ["postgres_exporter:9187"]
